---
- name: Get user ID
  hosts: all
  vars:
    myuser: "dev_user"
  tasks:
    - name: Get {{ myuser }} info
      getent:
        database: passwd
        key: "{{ myuser }}"
    - debug:
        msg:
          - "{{ myuser }} uid: {{ getent_passwd[myuser].1 }}"
