---
  - name: Install Flask and run webapplication
    hosts: ubuntu
    become: true
    become_user: root
    tasks:
      - name: Update
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Upgrade 
        apt: upgrade=dist force_apt_get=yes

      - name: Install Python
        apt:
          name: python-pip
          force_apt_get: yes
          state: latest

      - name: Install Flask 
        pip:
          name: flask
          state: latest
          executable: pip  

      - name: Copy hello.py to remote host
        copy:
          src: /home/student/Documents/PXL/Automation/automation2223/week3/Flask/hello.py
          dest: /tmp/hello.py
          mode: '0644'

      - name: Execute hello.py
        command: python /tmp/hello.py 
