version: '3.7'
services:
 mysql:
   image: mysql
   environment:
      MYSQL_ROOT_PASSWORD: rootexapwd
      MYSQL_DATABASE: demo
      MYSQL_USER: examen
      MYSQL_PASSWORD: userexapwd
   ports:
      - 3306:3306
   secrets:
   - rootpwd
   - userpwd
   restart: always
   volumes:
    - /home/student/mysql-data:/var/lib/mysql
 phpmyadmin:
   image: phpmyadmin
   ports:
      - 80:80
   environment:
     PMA_HOST: 172.21.0.1
     PMA_USER: examen
     PMA_PASSWORD: userexapwd
   secrets:
   - userpwd
   restart: always

secrets:
 rootpwd:
  file: rootpwd.txt
 userpwd:
  file: userpwd.txt
