---
- hosts: kubernetes_controller
  become: true
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="10.128.102.10" --pod-network-cidr=10.128.102.0/24

    - name: Allow others to read admin.conf
      file:
        path: /etc/kubernetes/admin.conf
        mode: "0644"

    - name: Setup kubeconfig for student user
      command: "{{ item }}"
      with_items:
      - mkdir -p /home/student/.kube
      - cp -f /etc/kubernetes/admin.conf /home/student/.kube/config
      - chown student:student /home/student/.kube/config

    # - name: Install Weave CNI
    #   become: false
    #   become_user: student
    #   command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    
    - name: Generate join command
      command: kubeadm token create --print-join-command 
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
