---
- hosts: pe2
  become: true
  tasks:
    - name: Install 'httpd', 'firewalld' and 'openssh-server'
      ansible.builtin.package:
        name:
          - httpd ## Extra 2 - Ansible: apache (40%)
          - firewalld
          - openssh-server
          - iptables
        state: present

    - name: Start apache service
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
          - httpd ## Extra 2 - Ansible: apache (40%)
          - firewalld
          - openssh-server
          - iptables
    
    - name: Add the user "{{ user_name }}" with a specific password
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        home: "/home/{{ user_name }}"

    - name: Set authorized key taken from variable
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ ssh_public_key }}"

    - name: Permit traffic to port 22
      ansible.posix.firewalld:
        port: "22/tcp"
        permanent: true
        state: enabled

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/info.txt
        dest: "/home/{{ user_name }}/info.txt"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"

    # Extra 1 - Ansible: $PATH (10%)

    - name: Display '$PATH' variable value
      ansible.builtin.debug:
        var: ansible_env.PATH

    ## Extra 2 - Ansible: apache (40%)

    - name: Start apache service
      ansible.builtin.service:
        name: httpd
        state: started 
    
    - name: Allow connection to port 80
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ apache_index_src }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"