# tasks file for test_role
---
  - name: Install packages
    ansible.builtin.package: 
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
      
  - name: Start and enable services
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Check if doc_root exists
    ansible.builtin.command: ls "{{ doc_root }}"
    register: directory_exists
    ignore_errors: true

  - name: Create doc_root dir if nonexistent
    ansible.builtin.file:
      path: "{{ doc_root }}"
      state: directory
      mode: 0755
    when: directory_exists is failed
  
  - name: Check if index file exists
    ansible.builtin.command: ls {{ doc_root }}/index.html
    register: index_exists
    ignore_errors: true

  - name: Create the index.html file if nonexistent
    ansible.builtin.template:
      src: landing-page.html.j2
      dest: "{{ doc_root }}/index.html"
      mode: 0644
    when: index_exists is failed

  - name: Create Nginx conf file from template
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/conf.d/{{ site_name }}.conf
      mode: 0644
    notify: Restart Nginx
  
  - name: Allow incoming HTTP traffic
    firewalld:
      port: "{{ web_port }}/tcp"
      state: enabled
      immediate: true
      permanent: true
    notify: 
      - Restart firewalld 
