ALTER SESSION
SET NLS_TERRITORY = 'AMERICA';

ALTER SESSION
SET NLS_LANGUAGE = 'AMERICAN';

SET LINESIZE 200
SET PAGESIZE 30
SET SERVEROUTPUT ON FORMAT WRAPPED
SET AUTOPRINT ON
DEFINE_EDITOR="C:\Program Files\Notepad++\notepad++.exe"

