var1 = input("Geef een getal: ")
var1 = int(var1)
var2 = input("Geef nog een getal: ")
var2 = int(var2)
var3 = input("Geef een derde getal: ")
var3 = int(var3)
gemiddelde = ((var1+var2+var3)/3)
print(gemiddelde)
