---
- name: update and upgrade 
  hosts: allservers
  become: true
  become_user: root

  tasks:
      
    - name: Update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade 
      apt: upgrade=dist force_apt_get=yes
    
    - name: reboot machines
      ansible.builtin.reboot:
    
    # - name: Checking if reboot is needed
    #   register: reboot_required_file
    #   stat: path=/var/run/reboot-required get_md5=no

    # - name: Rebooting the system when needed
    #   reboot: 
    #     msg: "Rebooting"
    #     connect_timeout: 5
    #     reboot_timeout: 300
    #     pre_reboot_delay: 0
    #     post_reboot_delay: 30
    #     test_command: uptime
    #   when: reboot_required_file.stat.exists

- name: deploy docker and netwrok
  hosts: dockerservers
  become: true
  become_user: root

  tasks:
                                                                                                                           
    - name: Download get-docker.sh script
      get_url:
        url: https://get.docker.com
        dest: ~/get-docker.sh
        mode: '0755'
        validate_certs: no
        force: yes
    
    - name: Execute docker shell
      shell: ~/get-docker.sh
      ignore_errors: yes
      no_log: true
      
    - name: Add the user to docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker

    - name: Create a network
      docker_network:
        name: service_net
      when: inventory_hostname != "server9"
