---
  - name: Install Flask and run webapplication
    hosts: rhel
    become: true
    become_user: root
    tasks:
      - name: Update & Ugrade
        yum:
          update_only: true

      - name: Install Python
        yum:
          name:
            - python3
            - pip
          state: latest
          update_cache: yes

      - name: Install Flask 
        pip:
          name: flask
          executable: pip3  
      
      - name: Create a directory fancydir
        file:
          path: /opt/fancydir
          state: directory
          mode: '0755'

      - name: Copy hello.py to remote host
        copy:
          src: "{{ src_path }}"
          dest: "{{ dest_path }}"
          mode: '0755'

      - name: Create systemd service file
        template:
          src: flask.service.j2
          dest: "{{ service_file_path }}"
        notify:
          - Reload systemd

      - name: Enable and start the service
        service:
          name: flask.service
          enabled: yes
          state: started

      #Trouble starting service? logs:
      #journalctl -u <name>.service
      #flask.py illegal name because
      # from flask import Flask

      - name: Install iptables package
        yum:
          name: iptables-services
          state: present
      
      - name: Ensure iptables service is running
        service:
          name: iptables
          state: started
          enabled: yes

      - name: Open Port 8080
        iptables:
          chain: INPUT
          action: insert
          protocol: tcp
          destination_port: 8080
          jump: ACCEPT        
          comment: 'Allow 8080'

      - name: Save current state of the firewall in system file
        community.general.iptables_state:
          state: saved
          path: /etc/sysconfig/iptables
        notify:
          - restart iptables

      #iptable steps:
      # install, start, allow, save, restart

    handlers:
      - name: Reload systemd
        systemd:
          name: flask.service
          daemon_reload: yes   
          
      - name: restart iptables
        service:
          name: iptables
          state: restarted
