---
  - name: Install and run app.py
    hosts: webservers
    become: true
    become_user: root
    tasks:
      - name: Install python
        yum:
          name: 
          - python3
          - pip
          state: latest
          update_cache: yes

      - name: Install dependencies
        pip:
          name: 
            - psutil
            - pyramid
            - waitress
          executable: pip3

      - name: Create a directory 'pyramid'
        file:
          path: /opt/pyramid
          state: directory
          mode: '0755'
        
      - name: Copy app.py to ec2 host
        copy:
          src: "{{ script_path }}"
          dest: /opt/pyramid/{{ script_name }}
          mode: '0755'


      - name: Create systemd service file
        template:
          src: app.service.j2
          dest: "{{ service_file_path }}"
        notify:
          - Reload systemd

      - name: Enable and start the service
        service:
          name: app.service
          enabled: yes
          state: started

    handlers:
      - name: Reload systemd
        systemd:
          daemon_reload: yes            