- hosts: all
  become: true

  tasks:
    - name: Install dependencies
      yum:
        name: 
        - python3
        - python3-pip
        - iptables-services
        state: present

    - name: Install pip packages
      pip:
        name: 
          - psutil
          - pyramid
          - waitress
          - distro
        state: present

    - name: Create pyramid dir
      file:
        path: /opt/pyramid
        state: directory
        mode: 0755
      
    - name: Copy app.py to server
      copy:
        src: app.py
        dest: /opt/pyramid/
        mode: 0644

    - name: Ensure iptables service is running
      service:
        name: iptables
        enabled: true

    - name: Open Port 5000
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 5000
        jump: ACCEPT    
      notify: 
        - Restart iptables

    - name: Create systemd service file
      template:
        src: app.service.j2
        dest: /etc/systemd/system/pyramid.service
      notify:
        - Reload systemd

    - name: Start pyramid service
      service:
        name: pyramid
        enabled: true
        state: started

    - name: Create user app_user
      user:
        name: app_user
        state: present
    
    - name: Change ownership of /opt/pyramid
      file:
        path: /opt/pyramid
        owner: app_user
        group: app_user
        recurse: true


  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes     

    - name: Restart iptables
      service:
        name: iptables
        state: restarted

