---
  - name: Install and run app.py
    hosts: webservers
    become: true
    become_user: root
    tasks:
      - name: Install python
        yum:
          name: 
          - python3
          - pip
          state: latest
          update_cache: yes

      - name: Install dependencies
        pip:
          name: 
            - psutil
            - pyramid
            - waitress
          executable: pip3

      - name: Create a directory 'pyramid'
        file:
          path: /opt/pyramid
          state: directory
          mode: '0755'
        
      - name: Copy app.py to ec2 host
        copy:
          src: "{{ script_path }}"
          dest: /opt/pyramid/{{ script_name }}
          mode: '0755'


      - name: Create systemd service file
        template:
          src: app.service.j2
          dest: "{{ service_file_path }}"
        notify:
          - Reload systemd

      - name: Enable and start the service
        service:
          name: app.service
          enabled: yes
          state: started
      
      - name: Install iptables package
        yum:
          name: iptables-services
          state: present
      
      - name: Ensure iptables service is running
        service:
          name: iptables
          state: started
          enabled: yes

      - name: Open Port 5000
        iptables:
          chain: INPUT
          protocol: tcp
          destination_port: 5000
          jump: ACCEPT        
          comment: 'Allow 5000'

      - name: Save iptables rules
        service:
          name: iptables
          state: restarted

      - name: Add the user app_user
        user:
          name: app_user
      
      - name: Recursively change ownership of a directory
        file:
          path: /opt/pyramid
          state: directory
          recurse: yes
          owner: app_user


    handlers:
      - name: Reload systemd
        systemd:
          daemon_reload: yes            
