---
- name: create users
  user:
    name: "{{ item }}"
    password: "{{ password | password_hash('sha512') }}"
    state: present
  loop: "{{ users }}"

- name: create web page directory
  file:
    path: "{{ doc_root }}"
    state: directory
    mode: 0755

- name: check if webpage already exists
  stat:
    path: "{{ doc_root }}/index.html"
  register: web_page

- name: copy webpage to dest if nonexistent
  copy:
    src: index.html
    dest: "{{ doc_root }}"
    mode: 0644
  when: not web_page.stat.exists

- name: create http-server service
  template:
    src: http-server.service.j2
    dest: "{{ service_dir }}/http-server.service"
    mode: 0644
    #group: musa
  notify: Restart http-server

- name: allow incoming traffic on 8080
  firewalld:
    port: "{{ web_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify: Restart firewalld
